### ISSUE TITLE
TargetEncoder can't  invoke fit_transform  on single col after having invoked fit_transform on mutil cols

### ISSUE THREAD

**Issue by valwu** [scikit-learn-contrib/category_encoders#267]
## Summary
running following code will crash
`
myn2 = np.array([
    ["A", "C", "Y"],
    ["A", "D", "Y"],
    ["B", "C", "X"]])
y = np.array([
    [1.0],
    [0.0],
    [1.0]])
resltnp2 = np.zeros((3, 3))
encoder = ce.target_encoder.TargetEncoder(return_df=False)
print(encoder.fit_transform(myn2[:, 0:3], y))
print(encoder.fit_transform(myn2[:, 0:1], y))
`
## Expected Outcome
[[0.54482357 0.91035286 0.54482357]
 [0.54482357 0.66666667 0.54482357]
 [0.66666667 0.91035286 0.66666667]]
[[0.54482357]
 [0.54482357]
 [0.66666667]]

## Actual Outcome

[[0.54482357 0.91035286 0.54482357]
 [0.54482357 0.66666667 0.54482357]
 [0.66666667 0.91035286 0.66666667]]
Traceback (most recent call last):
  File "D:\xx\keyprogram\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 987, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 993, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/xx/code/python/pylearn/src/learn/python/encoder.py", line 74, in <module>
    print(encoder.fit_transform(myn2[:, 0:1], y))
  File "D:\xx\keyprogram\anaconda3\lib\site-packages\category_encoders\target_encoder.py", line 258, in fit_transform
    return self.fit(X, y, **fit_params).transform(X, y)
  File "D:\xx\keyprogram\anaconda3\lib\site-packages\category_encoders\target_encoder.py", line 140, in fit
    self.ordinal_encoder = self.ordinal_encoder.fit(X)
  File "D:\xx\keyprogram\anaconda3\lib\site-packages\category_encoders\ordinal.py", line 141, in fit
    handle_missing=self.handle_missing
  File "D:\xx\keyprogram\anaconda3\lib\site-packages\category_encoders\ordinal.py", line 312, in ordinal_encoding
    if util.is_category(X[col].dtype):
  File "D:\xx\keyprogram\anaconda3\lib\site-packages\pandas\core\frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\xx\keyprogram\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 987, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 993, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1

Process finished with exit code 1
## Specifications

  - Version: 2.1.0
  - Platform: windows
  - Subsystem: python3.7

**Comment by PaulWestenthanner** [comment]
This is the issue described in #122 
#326 will fix it

**Comment by PaulWestenthanner** [comment]
close as #325 is merged
