### ISSUE TITLE
ValueError: buffer source array is read-only when using TargetEncoder within ColumnTransformer

### ISSUE THREAD

**Issue by melgazar9** [scikit-learn-contrib/category_encoders#286]
## Expected Behavior
return:
```
ColumnTransformer(n_jobs=9,
                  transformers=[('hc_pipeline',
                                 Pipeline(steps=[('functiontransformer',
                                                  FunctionTransformer(lambda x: x.astype(str)),
                                                 ('simpleimputer',
                                                  SimpleImputer(strategy='constant'))]),
                                 [cat_feature_1,
                                  cat_feature_2])])
```

## Actual Behavior

---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/sklearn/pipeline.py", line 740, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/sklearn/pipeline.py", line 376, in fit_transform
    return last_step.fit_transform(Xt, y, **fit_params_last_step)
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/category_encoders/utils.py", line 150, in fit_transform
    return self.fit(X, y, **fit_params).transform(X, y)
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/category_encoders/target_encoder.py", line 142, in fit
    self.mapping = self.fit_target_encoding(X_ordinal, y)
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/category_encoders/target_encoder.py", line 170, in fit_target_encoding
    stats = y.groupby(X[col]).agg(['count', 'mean'])
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/pandas/core/groupby/generic.py", line 246, in aggregate
    ret = self._aggregate_multiple_funcs(func)
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/pandas/core/groupby/generic.py", line 319, in _aggregate_multiple_funcs
    results[base.OutputKey(label=name, position=idx)] = obj.aggregate(func)
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/pandas/core/groupby/generic.py", line 240, in aggregate
    return getattr(self, func)(*args, **kwargs)
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/pandas/core/groupby/groupby.py", line 1394, in mean
    numeric_only=numeric_only,
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/pandas/core/groupby/groupby.py", line 1032, in _cython_agg_general
    obj._values, how, min_count=min_count
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/pandas/core/groupby/ops.py", line 585, in aggregate
    "aggregate", values, how, axis, min_count=min_count
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/pandas/core/groupby/ops.py", line 537, in _cython_operation
    result = self._aggregate(result, counts, values, codes, func, min_count)
  File "/home/melgazar/python36_venv/lib64/python3.6/site-packages/pandas/core/groupby/ops.py", line 599, in _aggregate
    agg_func(result, counts, values, comp_ids, min_count)
  File "pandas/_libs/groupby.pyx", line 618, in pandas._libs.groupby._group_mean
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-93-ac05c19cc2f7> in <module>
      5 ds_print('CC feature engineering...')
      6 feature_transformer_CC = PreprocessFeatures(preserve_vars = preserve_vars_CC,
----> 7                                             **feature_engineering_params).fit(X_train_CC, y_train_CC)
      8 # ds_print('NCC feature engineering...')
      9 # feature_transformer_NCC = PreprocessFeatures(preserve_vars = preserve_vars_NCC,

<ipython-input-86-e966f47c016b> in fit(self, X, y, remainder)
    160             ],
    161             remainder = remainder,
--> 162             n_jobs = self.n_jobs).fit(X, y)
    163 
    164         setattr(feature_transformer, 'feature_types', feature_types) # set an attribute for detected features

~/python36_venv/lib64/python3.6/site-packages/sklearn/compose/_column_transformer.py in fit(self, X, y)
    492         # we use fit_transform to make sure to set sparse_output_ (for which we
    493         # need the transformed data) to have consistent output type in predict
--> 494         self.fit_transform(X, y=y)
    495         return self
    496 

~/python36_venv/lib64/python3.6/site-packages/sklearn/compose/_column_transformer.py in fit_transform(self, X, y)
    529         self._validate_remainder(X)
    530 
--> 531         result = self._fit_transform(X, y, _fit_transform_one)
    532 
    533         if not result:

~/python36_venv/lib64/python3.6/site-packages/sklearn/compose/_column_transformer.py in _fit_transform(self, X, y, func, fitted)
    465                     message=self._log_message(name, idx, len(transformers)))
    466                 for idx, (name, trans, column, weight) in enumerate(
--> 467                         self._iter(fitted=fitted, replace_strings=True), 1))
    468         except ValueError as e:
    469             if "Expected 2D array, got 1D array instead" in str(e):

~/python36_venv/lib64/python3.6/site-packages/joblib/parallel.py in __call__(self, iterable)
   1040 
   1041             with self._backend.retrieval_context():
-> 1042                 self.retrieve()
   1043             # Make sure that we get a last message telling us we are done
   1044             elapsed_time = time.time() - self._start_time

~/python36_venv/lib64/python3.6/site-packages/joblib/parallel.py in retrieve(self)
    919             try:
    920                 if getattr(self._backend, 'supports_timeout', False):
--> 921                     self._output.extend(job.get(timeout=self.timeout))
    922                 else:
    923                     self._output.extend(job.get())

~/python36_venv/lib64/python3.6/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

/usr/lib64/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

/usr/lib64/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

ValueError: buffer source array is read-only

## Steps to Reproduce the Problem

  1. It column transformer works when using other sklearn fit methods, but fails on TargetEncoder for some reason.

Example

```
# works
hc_pipe = make_pipeline(
                         FunctionTransformer(lambda x: x.astype(str)),
                         SimpleImputer(strategy='constant'))
```

# fails
```
hc_pipe = make_pipeline(
                         FunctionTransformer(lambda x: x.astype(str)),
                         SimpleImputer(strategy='constant'),
                         TargetEncoder(smoothing=100,
                                                   return_df = False,
                                                   handle_missing = 'value',
                                                   handle_unknown = 'value',
                                                   min_samples_leaf = 10)
                        )
```

The above also fails without specifying any parameters within the TargetEncoder

**Comment by melgazar9** [comment]
Needed to update sklearn
